name: LaTeX Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install texlive-base texlive-latex-extra texlive-font-utils

      - name: Build LaTeX code
        run: |
          make build

      - name: Upload pdf
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: ./phdquali.pdf
